<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-04-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blog_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Laptop',
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptop'},
        ),
    ]
=======
# Generated by Django 4.1.5 on 2023-04-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blog_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Laptop',
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptop'},
        ),
    ]
>>>>>>> 5e59e769f249e9ade78b6cfbba69e48ad1ad9dd1
