<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-04-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_desktop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='price',
            new_name='prices',
        ),
    ]
=======
# Generated by Django 4.1.5 on 2023-04-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_desktop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='price',
            new_name='prices',
        ),
    ]
>>>>>>> 5e59e769f249e9ade78b6cfbba69e48ad1ad9dd1
