<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
=======
# Generated by Django 4.1.5 on 2023-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
>>>>>>> 5e59e769f249e9ade78b6cfbba69e48ad1ad9dd1
