<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_testimony_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='profession',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
=======
# Generated by Django 4.1.5 on 2023-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_testimony_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='profession',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
>>>>>>> 5e59e769f249e9ade78b6cfbba69e48ad1ad9dd1
